### ISSUE TITLE
231123 오전회의

### ISSUE THREAD

**Issue by crystalbaek** [DJMLteam2/DP_main#32]
### Done
- AWS DB 업로드
- 모델: pickle 완성
- 이미지 크롤링 완성

### Todo
- [ ] 프론트: 웹사이트 구성 개발 (검색, 메인페이지, 상세페이지) 
- [ ] 프론트: 메인페이지 검색 예시 추가
- [ ] 프론트: 지도 추가 -> 상세페이지에 넣기
- [ ] 모델: 경로 탐색 (주말 중)
- [ ] 데이터 컬럼 추가된 거 슬라이싱
- [ ] 태그 클릭 시, 검색 정보 고도화
- [ ] 크롤링 -> FASTapi에 추가
- [ ] 태블로 AWS 데이터 연결, 대시보드 시각화

※ 옵션으로 생각해볼 것
- [ ] 이미지 벡터화 [size: 256 x 256 x 3]
- [ ] 이미지 유사도 분석 [VGG 모델]

### 다음주 
- [ ] UI 완성
- [ ] 성능 최적화
- [ ] (이미지 유사도 모델링)

**Comment by crystalbaek** [comment]
https://26-isj5803.slack.com/files/U054SPWQCTG/F067P0TR4AU/20231123_100345.jpg

**Comment by crystalbaek** [comment]
![20231123_100345](https://github.com/DJMLteam2/DP_main/assets/132244611/23cd628c-8f92-413a-97e8-ad1d65f3cbb3)

**Comment by Sam1000won** [comment]
화긴
