### ISSUE TITLE
231103/ DP-Daily meeting 

### ISSUE THREAD

**Issue by doxgxxn** [DJMLteam2/DP_main#5]
### 현재 마일스톤 : ex) 데이터 수집 정리 v0.1.0

---

## TODO

- [x] mockup page 레이아웃 설정 [백승아, 서형원]
- [x] 모델 선택 및 DB 구성 [오동균, 이태경]  << 추가 조사 필요
- [x] 도커 파일 구축 [한지웅]

### 추가 제안

--- 

참석자: 백승아, 오동균, 서형원, 한지웅, 이태경

⭐ 작업 중 문제점은 코멘트 추가

--- 

### 남은 일 

모델 선택 및 DB 구성

**Comment by Sam1000won** [comment]
현제 도커 실행중..

**Comment by 8trider** [comment]
목업 초안 작성 및 배포 https://mockup.fly.dev/

**Comment by doxgxxn** [comment]
모델 참고
https://huggingface.co/microsoft/tapex-large-finetuned-wtq

모델 튜닝 방법?
https://wikidocs.net/166801
